rawData<- read.table( file = "household_power_consumption.txt",stringsAsFactors = FALSE , header = TRUE, sep =";" )
subsetData <- subset(rawData,Date == "1/2/2007" | Date =="2/2/2007")
png("f:\\Plot1.png", width=480, height=480)
with(subsetData, hist(as.numeric(Global_active_power), col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)"))
dev.off()