rawData<- read.table( file = "household_power_consumption.txt",stringsAsFactors = FALSE , header = TRUE, sep =";" )
subsetData <- subset(rawData,Date == "1/2/2007" | Date =="2/2/2007")
timeStamp<- strptime(paste( subsetData$Date, subsetData$Time, sep = " " ), format = "%d/%m/%Y %H:%M:%S")
png("Plot2.png", width=480, height=480)
plot(timeStamp,subsetData$Global_active_power,type="l" ,xlab="", ylab="Global Active Power (kilowatts)")
dev.off()